# Generated by Django 4.1.6 on 2023-02-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='phone',
        ),
    ]
