# Generated by Django 4.1.6 on 2023-02-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_otp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
