# Generated by Django 4.1.6 on 2023-02-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP',
        ),
    ]
