# Generated by Django 4.1.6 on 2023-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, null=True, to='product.ip'),
        ),
    ]
