# Generated by Django 4.1.6 on 2023-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_product_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdescription',
            name='title',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
