# Generated by Django 4.1.6 on 2023-02-10 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_color_title_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی کلی', 'verbose_name_plural': 'دسته بندی های کلی'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'IP', 'verbose_name_plural': 'IPs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'زیر دسته بندی', 'verbose_name_plural': 'زیر دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='subdescription',
            options={'verbose_name': 'توضیح', 'verbose_name_plural': 'توضیحات'},
        ),
        migrations.AlterModelOptions(
            name='subset',
            options={'verbose_name': 'زیر مجموعه', 'verbose_name_plural': 'زیر مجموعه ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان رنگ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=25, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='دسته بندی کلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='product.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(0)], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory', verbose_name='زیر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subset', verbose_name='زیر مجموعه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=90, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=90, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, to='product.ip', verbose_name='بازذیذ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='key',
            field=models.CharField(max_length=20, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=70, verbose_name='مقدار ویژگی'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='subdescription',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='subdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_descriptions', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='subdescription',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='subset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='product.subcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='subset',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='subset',
            name='title',
            field=models.CharField(max_length=20, verbose_name='عنوان'),
        ),
    ]
