# Generated by Django 4.1.6 on 2023-02-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_subcategory_parent_subset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subset'),
            preserve_default=False,
        ),
    ]
