# Generated by Django 4.1.6 on 2023-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_subset'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title_en',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
