# Generated by Django 4.1.6 on 2023-02-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_color_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_warranty',
        ),
    ]
