# Generated by Django 4.1.6 on 2023-02-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_property_key_titleproperty_alter_property_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.DeleteModel(
            name='TitleProperty',
        ),
    ]
