# Generated by Django 4.1.6 on 2023-02-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
    ]
