# Generated by Django 4.1.6 on 2023-02-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
        migrations.AddField(
            model_name='subset',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
