# Generated by Django 4.1.6 on 2023-02-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_alter_color_options_and_more'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نطر', 'verbose_name_plural': 'نطرات'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'پرسش و پاسخ', 'verbose_name_plural': 'پرسش و پاسخ ها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=models.CharField(max_length=125, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='question',
            name='full_name',
            field=models.CharField(max_length=125, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_parent',
            field=models.BooleanField(default=False, verbose_name='دارای والد ؟'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='comment.question', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='question',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='product.product', verbose_name='محصول'),
        ),
    ]
