# Generated by Django 4.1.6 on 2023-02-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
