# Generated by Django 4.1.6 on 2023-02-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='order',
        ),
    ]
